# Technical Path {#technical-learning-ml}

## Introduction

### Opening Thoughts
* There are many ways to learn technical material. Paid courses, YouTube videos, blog posts, and books are all equally effective based on your learning style. The content in the following sections tries to have a healthy balance of all content types. 
* By default, all of the recommended learning content is free. There are additional resources mentioned where you might have to pay for. These serve as additional avenues to strengthen the concepts and techniques learned in the initial free content. 
* Machine Learning falls into two camps of programming languages, those who use R and those who leverage Python. Both have their strengths and weaknesses. All learning content will have an equal amount of resources for both R and Python.

### R or Python?
* Short answer: Eventually you will have to learn both to become a successfully data practitioner, but if you could only pick one choose Python. 

### Getting the Most out of Learning
* [Deliberate practice](https://jamesclear.com/deliberate-practice-theory) is the best way of getting the learning to stick, and to rapidly evolve your skills. 
* **Whenever you learn something new in the data and AI world, it's best to usually apply it immediately to a real world project within your job or company.** By using a real world problem to practice what you just learned, you're able to reinforce the new knowledge into your long term memory while at the same time driving impact in your job by solving real problems. What a bonus! Be careful about only working on "toy datasets", which is public data that has been beat to death by hundreds of blogs and courses. The real world of data is messy and unpredictable, so working on things related to your current job or company gets you comfortable with that uncertainty even faster. 
* Don't feel bad looking up things on Bing/Google. Every technical person who works with computers today most likely looks up things online every day. Software syntax takes time to learn, and some of the best engineers still don't remember all the ins and outs of a language. When it doubt look it up online! Sites like Stack Overflow will quickly become your best friend as you try to work through issues in your code.

## Installing Software

### Python
* [Coding Tools for Python Development](https://docs.microsoft.com/en-us/learn/modules/install-code-tools-python-nasa/)
* [VSCode Python Setup](https://www.youtube.com/playlist?list=PLo32uKohmrXt7VB91DLB-hMcDcWswE53Y)
* [Install Packages - Windows](https://www.activestate.com/resources/quick-reads/python-package-installation-on-windows/)
* [Install Packages - Mac](https://blog.quantinsti.com/installing-python-packages/)

### R
* [Installing R and RStudio](https://rstudio-education.github.io/hopr/starting.html)
* [Install Packages](https://rstudio-education.github.io/hopr/packages2.html)

## Data Analysis and Manipulation

### Python
* Pick one of the following
    + [Option 1 - Free Code Camp](https://www.freecodecamp.org/learn/data-analysis-with-python/)
    + [Option 2 - Zero to Pandas](https://www.youtube.com/watch?v=EsDFiZPljYo&list=PLWKjhJtqVAblvI1i46ScbKV2jH1gdL7VQ)
    + [Option 3 - 12 Hour Course](https://www.youtube.com/watch?v=EsDFiZPljYo&list=PLWKjhJtqVAblvI1i46ScbKV2jH1gdL7VQ)
* [Exploratory Reports](https://www.youtube.com/watch?v=-Cdv9C9hLeE)

### R

* [Basics of R](https://rstudio-education.github.io/hopr/index.html)
* [Manipulating Data](https://r4ds.had.co.nz/index.html) (skip "Model" chapter)
* [Automating Excel in R](https://www.youtube.com/watch?v=EMSkZOF-ZG8)
* [Business Reporting in RMarkdown](https://www.youtube.com/watch?v=mszKt0i4yuY)
* [Exploratory Reports](https://www.youtube.com/watch?v=ssVEoj54rx4)
* [Fundamental of Data Visualization](https://clauswilke.com/dataviz/)
* [R Graphics Cookbook](https://r-graphics.org/)

### Additional Resources

* [Explore and Analyze Data in Python:  Microsoft](https://docs.microsoft.com/en-us/learn/modules/explore-analyze-data-with-python/) - Python
* [Python for Data Analysis](https://www.oreilly.com/library/view/python-for-data/9781491957653/) - Python
* [Python for Excel](https://www.oreilly.com/library/view/python-for-excel/9781492080992/) - Python
* [Data Cleaning Tutorial: Kaggle](https://www.kaggle.com/learn/data-cleaning) - Python
* [Pandas Tutorial: Kaggle](https://www.kaggle.com/learn/pandas) - Python
* [Data Visualization Tutorial: Kaggle](https://www.kaggle.com/learn/data-visualization) - Python
* [Python Crash Course](https://www.amazon.com/Python-Crash-Course-2nd-Edition/dp/1593279280) - Python
* [Advancing Into Analytics](https://www.oreilly.com/library/view/advancing-into-analytics/9781492094333/) - Python/R
* [Python and R for the Modern Data Scientist](https://www.oreilly.com/library/view/python-and-r/9781492093398/) - Python/R
* [R Programming Tutorial: Learn the Basics of Statistical Computing](https://www.youtube.com/watch?v=_V8eKsto3Ug&list=PLWKjhJtqVAblQe2CCWqV4Zy3LY01Z8aF1&index=9) - R
* [Data Transformation Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf ) - R
* [R Basics: Harvard](https://www.classcentral.com/course/edx-data-science-r-basics-9253) - R


## Version Control

### High Level Overview

* [Git and GitHub for Beginners](https://www.youtube.com/watch?v=RGOj5yH7evk&t=491s)

### Python

* [VSCode Github Project Setup](https://www.youtube.com/watch?v=e-qQDuswx2I)

### R

* [Happy Git and GitHub for the useR](https://happygitwithr.com/)
* [Setup R Project from GitHub](https://www.youtube.com/watch?v=F7aYV0RPyD0)

### Additional Resources
* [Contribute to an Open-Source Project on GitHub](https://docs.microsoft.com/en-us/learn/modules/contribute-open-source/)

## Machine Learning Basics

### High Level Topics

* [Three Things to do when Starting Out in Data Science](https://www.youtube.com/watch?v=ilUbD7EoQnk)
* [Types of ML Models](https://www.youtube.com/watch?v=yN7ypxC7838)
* [Gradient Descent: Step-by-Step](https://www.youtube.com/watch?v=sDv4f4s2SB8)
* [ML Fundamentals: Cross Validation](https://www.youtube.com/watch?v=fSytzGwwBVw)

### Python

* [Intro to Machine Learning: Kaggle](https://www.kaggle.com/learn/intro-to-machine-learning)
* [Intermediate Machine Learning: Kaggle](https://www.kaggle.com/learn/intermediate-machine-learning)
* [Feature Egnineering: Kaggle](https://www.kaggle.com/learn/feature-engineering)
* [Exploratory Data Analysis #1](https://www.youtube.com/watch?v=-Cdv9C9hLeE)
* [Exploratory Data Analysis #2](https://www.youtube.com/watch?v=CCy0JAB_fbo)
* [Scikit-Learn Crash Course](https://www.youtube.com/watch?v=0B5eIE_1vpU)
* [PyCaret Guide](https://pycaret.org/guide/)

### R

* [Tidy Modeling with R](https://www.tmwr.org/index.html)
* [Intro to ML with Parsnip](https://www.youtube.com/watch?v=2Zcwa7HPg5w&list=PLo32uKohmrXvDwyyty6pC4mcWER5tSdmO&index=10)
* [Supervised ML Case Studies in R](https://supervised-ml-course.netlify.app/)
* [Exploratory Data Analysis](https://www.youtube.com/watch?v=ssVEoj54rx4)
* [Business Reporting in R with Rmarkdown](https://www.youtube.com/watch?v=mszKt0i4yuY)

### Additional Resources

* [PCA Main Ideas](https://www.youtube.com/watch?v=HMOI_lkzW08)
* [Introduction to Machine Learning: Microsoft](https://docs.microsoft.com/en-us/learn/modules/introduction-to-machine-learning/) - Python
* [Introduction to Machine Learning : Udemy](https://www.classcentral.com/course/udemy-introduction-to-data-science-using-python-25723) - Python
* [Machine Learning for Beginners](https://github.com/microsoft/ML-For-Beginners) - Python
* [Best Python Machine Learning Libraries](https://github.com/ml-tooling/best-of-ml-python) - Python
* [Analytical Skills for AI & Data Science](https://learning.oreilly.com/library/view/analytical-skills-for/9781492060932/) - Python
* [Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow](https://learning.oreilly.com/library/view/hands-on-machine-learning/9781492032632/) - Python
* [Microsoft Approved Data Science Learning Resources](https://medium.com/data-science-at-microsoft/data-science-learning-resources-193ccf6fafb) - Python/R
* [Introduction to Statistical Learning](https://www.statlearning.com/) - R
* [Companion Book to Introduction to Statistical Learning](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/index.html) - R 
* [R Cheat Sheet](https://www.business-science.io/r-cheatsheet?utm_content=buffer832d4&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) - R
* [Practical Data Science with R](https://learning.oreilly.com/library/view/practical-data-science/9781617295874/) - R

## Regression

### High Level Topics

* [Making Friends with Regression](https://www.youtube.com/watch?v=WNvOtwP_yf4)
* [Evaluation Metrics for Regression Models](https://www.analyticsvidhya.com/blog/2021/05/know-the-best-evaluation-metrics-for-your-regression-model/#:~:text=%20Know%20The%20Best%20Evaluation%20Metrics%20for%20Your,is%20clear%20by%20the%20name%20itself%2C...%20More%20)

### Python

* [Train and Evaluate Regression Models: Microsoft](https://docs.microsoft.com/en-us/learn/modules/train-evaluate-regression-models/)
* [Train and Understand Regression Models: Microsoft](https://docs.microsoft.com/en-us/learn/modules/understand-regression-machine-learning/)
* [PyCaret Tutorials](https://pycaret.readthedocs.io/en/latest/tutorials.html#regression)
* [E-Commerce Tutorial](https://github.com/ishikkkkaaaa/ML-Projects/tree/main/1-E%20COMMERCE)
* [USA Housing Tutorial](https://github.com/ishikkkkaaaa/ML-Projects/tree/main/2-USA%20housing)

### R

* [Lasso Regression Tutorial](https://juliasilge.com/blog/lasso-the-office/)
* [Tune and Interpret Decision Trees Tutorial](https://juliasilge.com/blog/wind-turbine/)
* [Tune Random Forests Tutorial](https://juliasilge.com/blog/ikea-prices/)
* [Custom Metric Evaluation Tutorial](https://juliasilge.com/blog/nyc-airbnb/)
* [Bagging Tutorial](https://juliasilge.com/blog/astronaut-missions-bagging/)
* [Using Text as Features Tutorial](https://juliasilge.com/blog/tate-collection/)

### How Various Models Work

* [Fitting a Line to Data: Least Squares](https://www.youtube.com/watch?v=PaFPbb66DxQ)
* [Linear Models #1](https://www.youtube.com/watch?v=nk2CQITm_eo)
* [Linear Models #2](https://www.youtube.com/watch?v=zITIFTsivN8)
* [Regularization #1](https://www.youtube.com/watch?v=Q81RR3yKn30)
* [Regularization #2](https://www.youtube.com/watch?v=NGf0voTMlcs)
* [Regularization #3](https://www.youtube.com/watch?v=1dKRdX9bfIo)
* [Decision Trees](https://www.youtube.com/watch?v=g9c66TUylZ4)
* [Random Forest](https://www.youtube.com/watch?v=J4Wdy0Wc_xQ)
* [Gradient Boost](https://www.youtube.com/watch?v=3CC4N4z3GJc)
* [XGBoost](https://www.youtube.com/watch?v=OtD8wVaFm6E)

### Additional Resources

* [Fitting a Curve to Data](https://www.youtube.com/watch?v=Vf7oJ6z2LCc)
* [Linear Regression and Gradient Descent: Stanford](https://www.youtube.com/watch?v=4b4MUYve_U8)

## Time Series

### High Level Topics

* [Time Series Forecasting with Machine Learning](https://www.youtube.com/watch?v=_ZQ-lQrK9Rg)
* [Forecasting: Principles and Practice](https://otexts.com/fpp3/intro.html) (Chapter 1)

### Python

* [Time Series Analysis in Python #1](https://www.youtube.com/watch?v=axjgEgBgIY0)
* [Time Series Analysis in Python #2](https://www.youtube.com/watch?v=sCl6CXZ2xBg)
* [Time Series Forecasting with XGBoost](https://www.youtube.com/watch?v=Wsfz3i1AXzY)
* [Introduction to Machine Learning with Time Series](https://www.youtube.com/watch?v=Wf2naBHRo8Q)

### R

* [Forecasting: Principles and Practice](https://otexts.com/fpp3/)
* [Introduction to Modeltime: Forecasting with Tidymodels](https://www.youtube.com/watch?v=-bCelif-ENY)
* [High Performance Time Series Forecasting](https://www.youtube.com/watch?v=elQb4VzRINg)
* [Arima Forecasting in R](https://www.youtube.com/watch?v=3znQUrREUC8)
* [Forecasting Multiple Time Series with Modeltime](https://www.youtube.com/watch?v=6RjYIOCnRMk)
* [Plotting Time Series in R](https://www.youtube.com/watch?v=Nf8FwFCJz2c)
* [Microsoft Finance Time Series Forecast Framework](https://microsoft.github.io/finnts/)

### How Various Models Work

* All regression models in the [Regression](#regression) chapter can be turned into time series models
* [Arima](https://otexts.com/fpp3/arima.html)
* [Exponential Smoothing](https://otexts.com/fpp3/expsmooth.html)

### Additional Learning Resources

* [Machine Learning for Time Series with Python](https://www.youtube.com/watch?v=cBojo1hsHiI) - Python
* [Practical Time Series Analysis](https://learning.oreilly.com/library/view/practical-time-series/9781492041641/) - Python
* [Time Series Forecasting: Business Science University](https://university.business-science.io/p/ds4b-203-r-high-performance-time-series-forecasting) - R

## Classification

### High Level Topics

* [Classification in Machine Learning](https://www.youtube.com/watch?v=pXdum128xww) (skip tutorial at end)
* [Confusion Matrix](https://www.youtube.com/watch?v=Kdsp6soqA7o)
* [Sensitivity and Specificity](https://www.youtube.com/watch?v=vP06aMoz4v8)
* [ROC and AUC](https://www.youtube.com/watch?v=4jRBRDbJemM)

### Python

* [Train and Evaluation Classification Models: Microsoft](https://docs.microsoft.com/en-us/learn/modules/train-evaluate-classification-models/)
* [Create and Understand Classification Models: Microsoft](https://docs.microsoft.com/en-us/learn/modules/understand-classification-machine-learning/)
* [Confusion Matrix and Class Imbalance: Microsoft](https://docs.microsoft.com/en-us/learn/modules/machine-learning-confusion-matrix/)
* [Measure and Optimize Model Performance: Microsoft](https://docs.microsoft.com/en-us/learn/modules/optimize-model-performance-roc-auc/)
* [Hyperparameter Tuning with Random Forest: Microsoft](https://docs.microsoft.com/en-us/learn/modules/machine-learning-architectures-and-hyperparameters/)
* [PyCaret Tutorials](https://pycaret.readthedocs.io/en/latest/tutorials.html#classification)
* [Titanic Tutorial](https://github.com/ishikkkkaaaa/ML-Projects/tree/main/3-Titanic%20project)
* [Advertising Tutorial](https://github.com/ishikkkkaaaa/ML-Projects/tree/main/4-advertising%20project(logitic%20regression))
* [Loan Tutorial](https://github.com/ishikkkkaaaa/ML-Projects/tree/main/6-Loan%20project)

### R

* [Logistic Regression](https://www.youtube.com/watch?v=Qi-sVE0SWFc)
* [Hotel Bookings Tutorial](https://juliasilge.com/blog/hotels-recipes/)
* [Water Source Availability Tutorial](https://juliasilge.com/blog/water-sources/)
* [Beach Volleyball Tutorial](https://juliasilge.com/blog/xgboost-tune-volleyball/)
* [Volcano Eruptions Tutorial](https://juliasilge.com/blog/multinomial-volcano-eruptions/)
* [Food Consumption Tutorial](https://juliasilge.com/blog/food-hyperparameter-tune/)

### How Various Models Work

* [Logistic Regression](https://www.youtube.com/watch?v=yIYKR4sgzI8)
* [K-Nearest Neighbors](https://www.youtube.com/watch?v=HVXime0nQeI)
* [Decision Trees #1](https://www.youtube.com/watch?v=_L39rN6gz7Y)
* [Decision Trees #2](https://www.youtube.com/watch?v=wpNl-JwwplA)
* [Random Forest](https://www.youtube.com/watch?v=J4Wdy0Wc_xQ)
* [Gradient Boost](https://www.youtube.com/watch?v=jxuNLH5dXCs)
* [XGBoost](https://www.youtube.com/watch?v=8b1JEDvenQU)

### Additional Learning Resources

* [Locally Weighted and Logistic Regression: Stanford](https://www.youtube.com/watch?v=8b1JEDvenQU)
* [Supervised Machine Learning: Coursera](https://www.classcentral.com/course/supervised-learning-classification-20945) - Python
* [Classification Bootcamp: Udemy](https://www.classcentral.com/course/udemy-machine-learning-classification-38705) - Python
* [Machine Learning Classification: Coursera](https://www.classcentral.com/course/ml-classification-4219) - Python

## Unsupervised Learning

### Python

* [Train and Evaluate Clustering Models](https://docs.microsoft.com/en-us/learn/modules/train-evaluate-cluster-models/)
* [PyCaret Clustering Tutorial](https://pycaret.readthedocs.io/en/latest/tutorials.html#clustering)
* [PyCaret Anomaly Detection Tutorial](https://pycaret.readthedocs.io/en/latest/tutorials.html#anomaly-detection)
* [PCA Tutorial](https://github.com/ishikkkkaaaa/ML-Projects/tree/main/7-Breast%20cancer)

### R

* [PCA Tutorial](https://juliasilge.com/blog/un-voting/)
* [PCA and UMAP Tutorial](https://juliasilge.com/blog/cocktail-recipes-umap/)
* [Visualizing PCA in R](https://www.youtube.com/watch?v=X4wsXba_tZI)

### How Various Models Work

* [K-Means Clustering](https://www.youtube.com/watch?v=4b5d3muPQmA)
* [PCA](https://www.youtube.com/watch?v=FgakZw6K1QQ&list=PLblh5JKOoLUIcdlgu78MnlATeyx4cEVeR&index=1)

## Natural Language Processing

### Python

* [Natural Language Processing: Kaggle](https://www.kaggle.com/learn/natural-language-processing)
* [Explore Natural Language Processing in Azure: Microsoft](https://docs.microsoft.com/en-us/learn/paths/explore-natural-language-processing/)
* [PyCaret Tutorial](https://pycaret.readthedocs.io/en/latest/tutorials.html#natural-language-processing)

### R

* [Text Mining in R](https://www.tidytextmining.com/)
* [Text Mining with Tidy Data Principles](https://juliasilge.shinyapps.io/learntidytext/)
* [Supervised Machine Learning for Text Analysis](https://smltar.com/)

### Additional Resources

* [Practical Natural Language Processing](https://learning.oreilly.com/library/view/practical-natural-language/9781492054047/) - Python
* [Natural Language Processing with Python and spaCy](https://learning.oreilly.com/library/view/natural-language-processing/9781098122652/) - Python
* [Applied Text Analysis](https://learning.oreilly.com/library/view/applied-text-analysis/9781491963036/) - Python
* [Introduction to Natural Language Processing with PyTorch: Microsoft](https://docs.microsoft.com/en-us/learn/modules/intro-natural-language-processing-pytorch/) - Python

## Deep Learning

### High Level Topics

* [Deep Learning Crash Course](https://www.youtube.com/watch?v=VyWAvY2CF9c)
* [Neural Networks](https://www.youtube.com/playlist?list=PLblh5JKOoLUIxGDQs4LFFD--41Vzf-ME1)

### Python

* [Practical Deep Learning for Coders](https://course.fast.ai/)
* [Train and Evaluate Deep Learning Models: Microsoft](https://docs.microsoft.com/en-us/learn/modules/train-evaluate-deep-learn-models/)

### R

* [Deep Learning with Tidymodels, Torch, and Tabnet](https://www.youtube.com/watch?v=GuboAGHDgas)

### Additional Resources


* [Andrew Ng: Deep Learning, Education, and Real-World AI](https://www.youtube.com/watch?v=0jspaMLxBig)
* [Nuts and Bolts of Applying Deep Learning](https://www.youtube.com/watch?v=F1ka6a13S9I)
* [History of Deep Learning](https://www.youtube.com/watch?v=mTtDfKgLm54)
* [Deep Learning for Coders with fastai and PyTorch](https://learning.oreilly.com/library/view/deep-learning-for/9781492045519/) - Python
* [Deep Learning: Coursera](https://www.coursera.org/specializations/deep-learning#courses) - Python
* [Computer Vision Tutorial: Kaggle](https://www.kaggle.com/learn/computer-vision) - Python
* [Deep Learning with R](https://learning.oreilly.com/library/view/deep-learning-with/9781617295546/) - R

## Model Interpretability

### High Level Topics

* [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/)

### Python

* [Machine Learning Explainability: Kaggle](https://www.kaggle.com/learn/machine-learning-explainability)
* [interpretML](https://github.com/interpretml/interpret)

### R

* [vip: Variable Importance Plots](https://koalaverse.github.io/vip/index.html)
* [Model Interpretability Tutorial](https://juliasilge.com/blog/wind-turbine/)
* [Partial Dependence Plots with Tidymodels and DALEX](https://juliasilge.com/blog/mario-kart/)

## AI Ethics and Fairness

### High Level Topics

* [Intro to AI Ethics: Kaggle](https://www.kaggle.com/learn/intro-to-ai-ethics)
* [Fairness and Machine Learning](https://fairmlbook.org/)
* [What Happens when an Algorithm Cuts Your Healthcare](https://www.theverge.com/2018/3/21/17144260/healthcare-medicaid-algorithm-arkansas-cerebral-palsy)

### Python

* [Fairlearn](https://fairlearn.org/)
* [Data Ethics in Deep Learning](https://course.fast.ai/videos/?lesson=5)

## Web Apps

### R

* [A Gentle Introduction to creating R Shiny Web Apps](https://www.youtube.com/watch?v=jxsKUxkiaLI)
* [Shiny Walkthrough](https://www.youtube.com/watch?v=eoeLn8SyDW8)
* [Building Predictive Web Applications with R Shiny](https://www.youtube.com/watch?v=oegRVT262Ig)
* [Build Interactive Data-Driven Web Apps With R Shiny](https://www.freecodecamp.org/news/build-interactive-data-driven-web-apps-with-r-shiny/)
* [Engineering Production Grade Shiny Apps](https://engineering-shiny.org/)
* [Outstanding User Interfaces with Shiny](https://unleash-shiny.rinterface.com/index.html)

## Production on Azure

## Life as a Data Scientist