# on:
#   push:
#      branches:
#        - main
# 
#   
# 
# name: renderbook
# 
# jobs:
#   bookdown:
#     name: Render-Book
#     runs-on: macOS-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: r-lib/actions/setup-r@v1
#       - uses: r-lib/actions/setup-pandoc@v1
#       - name: Install rmarkdown
#         run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
#       - name: Render Book
#         run: Rscript -e 'bookdown::render_book("book-content")'
#       - uses: actions/upload-artifact@v1
#         with:
#           name: _book
#           path: book-content/_book/
#   
# # Need to first create an empty gh-pages branch
# # see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# # and also add secrets for a GH_PAT and EMAIL to the repository
# # gh-action from Cecilapp/GitHub-Pages-deploy
#   checkout-and-deploy:
#    runs-on: ubuntu-latest
#    needs: bookdown
#    steps:
#      - name: Checkout
#        uses: actions/checkout@master
#      - name: Download artifact
#        uses: actions/download-artifact@v1.0.0
#        with:
#          # Artifact name
#          name: _book # optional
#          # Destination path
#          path: book-content/_book/ # optional
#      - name: Deploy to GitHub Pages
#        uses: Cecilapp/GitHub-Pages-deploy@master
#        env:
#           EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
#           GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
#           BUILD_DIR: book-content/_book/                     # "_site/" by default

# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: bookdown

jobs:
  bookdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v1

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: book-content/_bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Build site
        run: Rscript -e 'bookdown::render_book("book-content"), quiet = TRUE)'

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: book-content/_book
 
